ALTER TABLE bids ADD COLUMN IF NOT EXISTS decline_reason TEXT;
ALTER TABLE bids ADD COLUMN IF NOT EXISTS counter_amount DECIMAL(12, 2);
ALTER TABLE bids ADD COLUMN IF NOT EXISTS counter_by UUID REFERENCES users(id);
